install: 
  - "pip install -r requirements.txt"
  - "echo \"SECRET_KEY = ''blabla''\nEMAIL_HOST_USER = ''email_user@host.com''\nEMAIL_HOST_PASSWORD = ''password''\nGITHUB_TOKEN = ''321abc''\nZOTERO_KEY = ''TODO''\" > ./app/secrets.py"
language: python
python: 
  - "3.8"
  - 3.9-dev
script: "python ./manage.py test || python3 ./manage.py test"
