language: python
python:
  - "3.8"
  - "3.9-dev"
services:
  - mysql
install:
  - "pip install -r requirements.txt"
  - "echo 'django-secret: \'blabla\'\nemail-password: \'password\'\ngithub-token: \'321abc\'\nzotero-key: \'TODO\'\n\n' > ./secrets.yml"
script: python ./manage.py test || python3 ./manage.py test